runtime: php72

env_variables:
  APP_NAME=Laravel
  APP_ENV=local
  APP_KEY=base64:5C8slWRRjR2KLLX0nOg6sDuXw1S4rCqlYWSF4xNadcg=
  APP_DEBUG=true
  APP_URL=http://localhost

  LOG_CHANNEL=stack
  LOG_DEPRECATIONS_CHANNEL=null
  LOG_LEVEL=debug

  DB_CONNECTION=mysql
  DB_HOST=x8autxobia7sgh74.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
  DB_PORT=3306
  DB_DATABASE=efasxn02vpittfkw
  DB_USERNAME=nfh7vrb6j9gdqywj
  DB_PASSWORD=gqzop6gvb3rlx634

  BROADCAST_DRIVER=log
  CACHE_DRIVER=file
  FILESYSTEM_DRIVER=local
  QUEUE_CONNECTION=sync
  SESSION_DRIVER=file
  SESSION_LIFETIME=120

  MEMCACHED_HOST=127.0.0.1

  REDIS_HOST=127.0.0.1
  REDIS_PASSWORD=null
  REDIS_PORT=6379

  MAIL_MAILER=smtp
  MAIL_HOST=mailhog
  MAIL_PORT=1025
  MAIL_USERNAME=null
  MAIL_PASSWORD=null
  MAIL_ENCRYPTION=null
  MAIL_FROM_ADDRESS=null
  MAIL_FROM_NAME="${APP_NAME}"

  AWS_ACCESS_KEY_ID=
  AWS_SECRET_ACCESS_KEY=
  AWS_DEFAULT_REGION=us-east-1
  AWS_BUCKET=
  AWS_USE_PATH_STYLE_ENDPOINT=false

  PUSHER_APP_ID=
  PUSHER_APP_KEY=
  PUSHER_APP_SECRET=
  PUSHER_APP_CLUSTER=mt1

  MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

  JWT_SECRET=iOjEj2HbwFKA5wnFpn4FXOjgl00wUoSL2O1IYDNm4P9vPXmt4FkNaweeYhj0ZAVb

  APP_KEY: YOUR_APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
